# we are extending everything from tomcat:8.5.29 image ...
FROM tomcat:8.5.29
MAINTAINER mbelniak
RUN apt-get update && apt-get install -y vim
COPY e-pogoda24.info.jks /usr/local/
COPY tomcat-users.xml /usr/local/tomcat/conf/
COPY context.xml /usr/local/tomcat/webapps/manager/META-INF/
COPY server.xml /usr/local/tomcat/conf/server.xml
# COPY path-to-your-application-war path-to-webapps-in-docker-tomcat
RUN rm -rf /usr/local/tomcat/webapps/ROOT
COPY target/ROOT.war /usr/local/tomcat/webapps/
