import walkSync from 'walk-sync';

export const cityList = [
    { displayName: 'Gdańsk', x: 400, y: 0 },
    { displayName: 'Szczecin', x: 250, y: 75 },
    { displayName: 'Olsztyn', x: 540, y: 35 },
    { displayName: 'Bydgoszcz', x: 410, y: 100 },
    { displayName: 'Poznań', x: 310, y: 135 },
    { displayName: 'Białystok', x: 650, y: 95 },
    { displayName: 'Siedlce', x: 640, y: 190 },
    { displayName: 'Warszawa', x: 540, y: 155 },
    { displayName: 'Zielona Góra', x: 240, y: 195 },
    { displayName: 'Kalisz', x: 380, y: 230 },
    { displayName: 'Łódź', x: 470, y: 235 },
    { displayName: 'Radom', x: 580, y: 250 },
    { displayName: 'Wrocław', x: 310, y: 280 },
    { displayName: 'Lublin', x: 670, y: 280 },
    { displayName: 'Opole', x: 380, y: 330 },
    { displayName: 'Kielce', x: 550, y: 310 },
    { displayName: 'Katowice', x: 450, y: 350 },
    { displayName: 'Kraków', x: 530, y: 375 },
    { displayName: 'Rzeszów', x: 630, y: 375 },
    { displayName: 'Sudety', x: 300, y: 350 },
    { displayName: 'Tatry', x: 515, y: 460 },
    { displayName: 'Bieszczady', x: 640, y: 470 }
];

export const imgSrcsDay = [
    require('../../img/generator/sun.png'),
    require('../../img/generator/z1.png'),
    require('../../img/generator/z1dd.png'),
    require('../../img/generator/z1ddds.png'),
    require('../../img/generator/z1dddsp.png'),
    require('../../img/generator/z1ddms.png'),
    require('../../img/generator/z1ddmsp.png'),
    require('../../img/generator/z1ddp.png'),
    require('../../img/generator/z1ds.png'),
    require('../../img/generator/z1dsp.png'),
    require('../../img/generator/z1md.png'),
    require('../../img/generator/z1mdds.png'),
    require('../../img/generator/z1mddsp.png'),
    require('../../img/generator/z1mdms.png'),
    require('../../img/generator/z1mdmsp.png'),
    require('../../img/generator/z1mdp.png'),
    require('../../img/generator/z1ms.png'),
    require('../../img/generator/z1msp.png'),
    require('../../img/generator/z1p.png'),
    require('../../img/generator/z2.png'),
    require('../../img/generator/z2dd.png'),
    require('../../img/generator/z2ddds.png'),
    require('../../img/generator/z2dddsp.png'),
    require('../../img/generator/z2ddp.png'),
    require('../../img/generator/z2ds.png'),
    require('../../img/generator/z2dsp.png'),
    require('../../img/generator/z2md.png'),
    require('../../img/generator/z2mdds.png'),
    require('../../img/generator/z2mddsp.png'),
    require('../../img/generator/z2mdms.png'),
    require('../../img/generator/z2mdmsp.png'),
    require('../../img/generator/z2mdp.png'),
    require('../../img/generator/z2ms.png'),
    require('../../img/generator/z2msp.png'),
    require('../../img/generator/z2p.png'),
    require('../../img/generator/z3.png'),
    require('../../img/generator/z3dd.png'),
    require('../../img/generator/z3ddds.png'),
    require('../../img/generator/z3dddsp.png'),
    require('../../img/generator/z3ddp.png'),
    require('../../img/generator/z3ds.png'),
    require('../../img/generator/z3dsp.png'),
    require('../../img/generator/z3md.png'),
    require('../../img/generator/z3mdds.png'),
    require('../../img/generator/z3mddsp.png'),
    require('../../img/generator/z3mdms.png'),
    require('../../img/generator/z3mdmsp.png'),
    require('../../img/generator/z3mdp.png'),
    require('../../img/generator/z3ms.png'),
    require('../../img/generator/z3msp.png'),
    require('../../img/generator/z3p.png'),
    require('../../img/generator/z4.png'),
    require('../../img/generator/z4dd.png'),
    require('../../img/generator/z4ddp.png'),
    require('../../img/generator/z4ds.png'),
    require('../../img/generator/z4dsp.png'),
    require('../../img/generator/z4md.png'),
    require('../../img/generator/z4mdp.png'),
    require('../../img/generator/z4ms.png'),
    require('../../img/generator/z4msp.png'),
    require('../../img/generator/z4p.png')
];

export const imgSrcsNight = [
    require('../../img/generator/moon.png'),
    require('../../img/generator/nz1.png'),
    require('../../img/generator/nz1dd.png'),
    require('../../img/generator/nz1ddds.png'),
    require('../../img/generator/nz1dddsp.png'),
    require('../../img/generator/nz1ddms.png'),
    require('../../img/generator/nz1ddmsp.png'),
    require('../../img/generator/nz1ddp.png'),
    require('../../img/generator/nz1ds.png'),
    require('../../img/generator/nz1dsp.png'),
    require('../../img/generator/nz1md.png'),
    require('../../img/generator/nz1mdds.png'),
    require('../../img/generator/nz1mddsp.png'),
    require('../../img/generator/nz1mdms.png'),
    require('../../img/generator/nz1mdmsp.png'),
    require('../../img/generator/nz1mdp.png'),
    require('../../img/generator/nz1ms.png'),
    require('../../img/generator/nz1msp.png'),
    require('../../img/generator/nz1p.png'),
    require('../../img/generator/nz2.png'),
    require('../../img/generator/nz2dd.png'),
    require('../../img/generator/nz2ddds.png'),
    require('../../img/generator/nz2dddsp.png'),
    require('../../img/generator/nz2ddp.png'),
    require('../../img/generator/nz2ds.png'),
    require('../../img/generator/nz2dsp.png'),
    require('../../img/generator/nz2md.png'),
    require('../../img/generator/nz2mdds.png'),
    require('../../img/generator/nz2mddsp.png'),
    require('../../img/generator/nz2mdms.png'),
    require('../../img/generator/nz2mdmsp.png'),
    require('../../img/generator/nz2mdp.png'),
    require('../../img/generator/nz2ms.png'),
    require('../../img/generator/nz2msp.png'),
    require('../../img/generator/nz2p.png'),
    require('../../img/generator/nz3.png'),
    require('../../img/generator/nz3dd.png'),
    require('../../img/generator/nz3ddds.png'),
    require('../../img/generator/nz3dddsp.png'),
    require('../../img/generator/nz3ddp.png'),
    require('../../img/generator/nz3ds.png'),
    require('../../img/generator/nz3dsp.png'),
    require('../../img/generator/nz3md.png'),
    require('../../img/generator/nz3mdds.png'),
    require('../../img/generator/nz3mddsp.png'),
    require('../../img/generator/nz3mdms.png'),
    require('../../img/generator/nz3mdmsp.png'),
    require('../../img/generator/nz3mdp.png'),
    require('../../img/generator/nz3ms.png'),
    require('../../img/generator/nz3msp.png'),
    require('../../img/generator/nz3p.png'),
    require('../../img/generator/z4.png'),
    require('../../img/generator/z4dd.png'),
    require('../../img/generator/z4ddp.png'),
    require('../../img/generator/z4ds.png'),
    require('../../img/generator/z4dsp.png'),
    require('../../img/generator/z4md.png'),
    require('../../img/generator/z4mdp.png'),
    require('../../img/generator/z4ms.png'),
    require('../../img/generator/z4msp.png'),
    require('../../img/generator/z4p.png')
];
