export const cityList = [
    { name: 'Szczecin', x: 70, y: 100 },
    { name: 'Gdańsk', x: 225, y: 40 },
    { name: 'Olsztyn', x: 400, y: 70 },
    { name: 'Białystok', x: 530, y: 145 },
    { name: 'Bydgoszcz', x: 250, y: 155 },
    { name: 'Zielona Góra', x: 50, y: 237 },
    { name: 'Poznań', x: 170, y: 212 },
    { name: 'Warszawa', x: 390, y: 215 },
    { name: 'Siedlce', x: 515, y: 245 },
    { name: 'Kalisz', x: 230, y: 290 },
    { name: 'Łódź', x: 325, y: 315 },
    { name: 'Radom', x: 455, y: 330 },
    { name: 'Wrocław', x: 130, y: 370 },
    { name: 'Opole', x: 240, y: 420 },
    { name: 'Katowice', x: 300, y: 465 },
    { name: 'Kielce', x: 410, y: 410 },
    { name: 'Lublin', x: 540, y: 345 },
    { name: 'Kraków', x: 375, y: 518 },
    { name: 'Rzeszów', x: 500, y: 505 },
    { name: 'Sudety', x: 120, y: 450 },
    { name: 'Tatry', x: 385, y: 600 },
    { name: 'Bieszczady', x: 547, y: 575 }
];

export const imgSrcsDay = {
    sun: require('../../img/generator/sun.png'),
    z1: require('../../img/generator/z1.png'),
    z1dd: require('../../img/generator/z1dd.png'),
    z1ddss: require('../../img/generator/z1ddss.png'),
    z1ddssp: require('../../img/generator/z1ddssp.png'),
    z1ddms: require('../../img/generator/z1ddms.png'),
    z1ddmsp: require('../../img/generator/z1ddmsp.png'),
    z1ddp: require('../../img/generator/z1ddp.png'),
    z1ds: require('../../img/generator/z1ds.png'),
    z1dsp: require('../../img/generator/z1dsp.png'),
    z1md: require('../../img/generator/z1md.png'),
    z1mdds: require('../../img/generator/z1mdds.png'),
    z1mddsp: require('../../img/generator/z1mddsp.png'),
    z1mdms: require('../../img/generator/z1mdms.png'),
    z1mdmsp: require('../../img/generator/z1mdmsp.png'),
    z1mdp: require('../../img/generator/z1mdp.png'),
    z1ms: require('../../img/generator/z1ms.png'),
    z1msp: require('../../img/generator/z1msp.png'),
    z1p: require('../../img/generator/z1p.png'),
    z2: require('../../img/generator/z2.png'),
    z2dd: require('../../img/generator/z2dd.png'),
    z2ddss: require('../../img/generator/z2ddss.png'),
    z2ddssp: require('../../img/generator/z2ddssp.png'),
    z2ddp: require('../../img/generator/z2ddp.png'),
    z2ds: require('../../img/generator/z2ds.png'),
    z2dsp: require('../../img/generator/z2dsp.png'),
    z2md: require('../../img/generator/z2md.png'),
    z2mdds: require('../../img/generator/z2mdds.png'),
    z2mddsp: require('../../img/generator/z2mddsp.png'),
    z2mdms: require('../../img/generator/z2mdms.png'),
    z2mdmsp: require('../../img/generator/z2mdmsp.png'),
    z2mdp: require('../../img/generator/z2mdp.png'),
    z2ms: require('../../img/generator/z2ms.png'),
    z2msp: require('../../img/generator/z2msp.png'),
    z2p: require('../../img/generator/z2p.png'),
    z3: require('../../img/generator/z3.png'),
    z3dd: require('../../img/generator/z3dd.png'),
    z3ddss: require('../../img/generator/z3ddss.png'),
    z3ddssp: require('../../img/generator/z3ddssp.png'),
    z3ddp: require('../../img/generator/z3ddp.png'),
    z3ds: require('../../img/generator/z3ds.png'),
    z3dsp: require('../../img/generator/z3dsp.png'),
    z3md: require('../../img/generator/z3md.png'),
    z3mdds: require('../../img/generator/z3mdds.png'),
    z3mddsp: require('../../img/generator/z3mddsp.png'),
    z3mdms: require('../../img/generator/z3mdms.png'),
    z3mdmsp: require('../../img/generator/z3mdmsp.png'),
    z3mdp: require('../../img/generator/z3mdp.png'),
    z3ms: require('../../img/generator/z3ms.png'),
    z3msp: require('../../img/generator/z3msp.png'),
    z3p: require('../../img/generator/z3p.png'),
    z4: require('../../img/generator/z4.png'),
    z4dd: require('../../img/generator/z4dd.png'),
    z4ddp: require('../../img/generator/z4ddp.png'),
    z4ds: require('../../img/generator/z4ds.png'),
    z4dsp: require('../../img/generator/z4dsp.png'),
    z4md: require('../../img/generator/z4md.png'),
    z4mdp: require('../../img/generator/z4mdp.png'),
    z4ms: require('../../img/generator/z4ms.png'),
    z4msp: require('../../img/generator/z4msp.png'),
    z4p: require('../../img/generator/z4p.png')
};

export const imgSrcsNight = {
    moon: require('../../img/generator/moon.png'),
    nz1: require('../../img/generator/nz1.png'),
    nz1dd: require('../../img/generator/nz1dd.png'),
    nz1ddss: require('../../img/generator/nz1ddss.png'),
    nz1ddssp: require('../../img/generator/nz1ddssp.png'),
    nz1ddms: require('../../img/generator/nz1ddms.png'),
    nz1ddmsp: require('../../img/generator/nz1ddmsp.png'),
    nz1ddp: require('../../img/generator/nz1ddp.png'),
    nz1ds: require('../../img/generator/nz1ds.png'),
    nz1dsp: require('../../img/generator/nz1dsp.png'),
    nz1md: require('../../img/generator/nz1md.png'),
    nz1mdds: require('../../img/generator/nz1mdds.png'),
    nz1mddsp: require('../../img/generator/nz1mddsp.png'),
    nz1mdms: require('../../img/generator/nz1mdms.png'),
    nz1mdmsp: require('../../img/generator/nz1mdmsp.png'),
    nz1mdp: require('../../img/generator/nz1mdp.png'),
    nz1ms: require('../../img/generator/nz1ms.png'),
    nz1msp: require('../../img/generator/nz1msp.png'),
    nz1p: require('../../img/generator/nz1p.png'),
    nz2: require('../../img/generator/nz2.png'),
    nz2dd: require('../../img/generator/nz2dd.png'),
    nz2ddss: require('../../img/generator/nz2ddss.png'),
    nz2ddssp: require('../../img/generator/nz2ddssp.png'),
    nz2ddp: require('../../img/generator/nz2ddp.png'),
    nz2ds: require('../../img/generator/nz2ds.png'),
    nz2dsp: require('../../img/generator/nz2dsp.png'),
    nz2md: require('../../img/generator/nz2md.png'),
    nz2mdds: require('../../img/generator/nz2mdds.png'),
    nz2mddsp: require('../../img/generator/nz2mddsp.png'),
    nz2mdms: require('../../img/generator/nz2mdms.png'),
    nz2mdmsp: require('../../img/generator/nz2mdmsp.png'),
    nz2mdp: require('../../img/generator/nz2mdp.png'),
    nz2ms: require('../../img/generator/nz2ms.png'),
    nz2msp: require('../../img/generator/nz2msp.png'),
    nz2p: require('../../img/generator/nz2p.png'),
    nz3: require('../../img/generator/nz3.png'),
    nz3dd: require('../../img/generator/nz3dd.png'),
    nz3ddss: require('../../img/generator/nz3ddss.png'),
    nz3ddssp: require('../../img/generator/nz3ddssp.png'),
    nz3ddp: require('../../img/generator/nz3ddp.png'),
    nz3ds: require('../../img/generator/nz3ds.png'),
    nz3dsp: require('../../img/generator/nz3dsp.png'),
    nz3md: require('../../img/generator/nz3md.png'),
    nz3mdds: require('../../img/generator/nz3mdds.png'),
    nz3mddsp: require('../../img/generator/nz3mddsp.png'),
    nz3mdms: require('../../img/generator/nz3mdms.png'),
    nz3mdmsp: require('../../img/generator/nz3mdmsp.png'),
    nz3mdp: require('../../img/generator/nz3mdp.png'),
    nz3ms: require('../../img/generator/nz3ms.png'),
    nz3msp: require('../../img/generator/nz3msp.png'),
    nz3p: require('../../img/generator/nz3p.png'),
    z4: require('../../img/generator/z4.png'),
    z4dd: require('../../img/generator/z4dd.png'),
    z4ddp: require('../../img/generator/z4ddp.png'),
    z4ds: require('../../img/generator/z4ds.png'),
    z4dsp: require('../../img/generator/z4dsp.png'),
    z4md: require('../../img/generator/z4md.png'),
    z4mdp: require('../../img/generator/z4mdp.png'),
    z4ms: require('../../img/generator/z4ms.png'),
    z4msp: require('../../img/generator/z4msp.png'),
    z4p: require('../../img/generator/z4p.png')
};
